language: ruby
rvm:
  - 1.8.7
script: bundle install; bundle exec rspec $SPEC
services:
  - mongodb

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - alex_wang@hsihealth.com
    on_success: change
    on_failure: always

env:
  - SPEC=spec
